// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUwooCkbt2LUph4tsIVKL9QrXgMh2RLZE',
    appId: '1:1024928426486:web:8ffce3b5c81a9ad746bfd7',
    messagingSenderId: '1024928426486',
    projectId: 'insta-clone-18224',
    authDomain: 'insta-clone-18224.firebaseapp.com',
    storageBucket: 'insta-clone-18224.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXnW7NkU8SWcrAsbQVOVpxOOQWI9q7N6c',
    appId: '1:1024928426486:android:1a17d5a911fea6b146bfd7',
    messagingSenderId: '1024928426486',
    projectId: 'insta-clone-18224',
    storageBucket: 'insta-clone-18224.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBllbuUgMMOHgx0L_fVSF1b_KhtcUPqOAI',
    appId: '1:1024928426486:ios:a65190a8952ac89046bfd7',
    messagingSenderId: '1024928426486',
    projectId: 'insta-clone-18224',
    storageBucket: 'insta-clone-18224.appspot.com',
    iosClientId: '1024928426486-50h2a2u82v3rahjcvdbjt8p9u98qhpg2.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );
}
